Api
MFatihMAR/efurni pull request #4
Opened 2020-09-27 20:01 UTC by PhantomCloak

Added base Controllers and Services

2020-09-27 20:09 UTC, MFatihMAR approved these changes

2020-09-27 20:11 UTC, MFatihMAR commented on efurni-api/Controllers/ProductController.cs
> +        ProductGroupingService _productGroupingService;
putting an explicitly `private` access modifiers might be good IMHO.

2020-09-27 20:13 UTC, MFatihMAR commented on efurni-api/Controllers/ProductController.cs
> +        [HttpGet("/products/popular")]
is that mean this endpoint will be access through `host.com/product/products/popular`? if so, I think `host.com/product/popular` might be a better/shorter option.

2020-09-27 20:14 UTC, MFatihMAR commented on efurni-api/Services/ProductGroupingService/Filters/FeaturedFilter.cs
> +namespace e_furniture.api.services
is there any specific reason to use `e_furniture` namespace rather than `efurni`?

2020-09-27 20:15 UTC, MFatihMAR commented on efurni-api/Services/ProductGroupingService/Filters/DiscountedFilter.cs
> +        public int Offset{get;set;}
please format .cs files to have consistent styling (where are the spaces here?) :)

2020-09-27 20:16 UTC, MFatihMAR commented on efurni-api/Controllers/ProductController.cs
> +            return Ok(products);
maybe `return _productGropService...` directly?

2020-09-27 20:16 UTC, MFatihMAR commented on efurni-api/Startup.cs
> +                option.InstanceName = "master";
grab these from config, do not hardcore them inline!

2020-09-27 20:18 UTC, MFatihMAR commented on efurni-api/efurni-api.csproj
> +    <RootNamespace>efurni_api</RootNamespace>
seems like our root namespace is `efurni_api`, I think it should be `efurni.api` and rest of the code should follow the same pattern.

2020-09-27 20:18 UTC, MFatihMAR commented on efurni-api/Controllers/ShoppingListController.cs
> +namespace e_furniture.api.controllers
namespace!

2020-09-27 20:18 UTC, MFatihMAR commented on efurni-shared/Models/ShoppingListItem.cs
> +    public partial class ShoppingListItem
is this a rename from the `Bag` version or a separate model? I'm confused...

2020-09-27 20:19 UTC, MFatihMAR commented on efurni-shared/Models/ShoppingListItem.cs
> +    public partial class ShoppingListItem
oh... I just saw the rename commit now.

2020-09-27 20:20 UTC, MFatihMAR commented on efurni-api/Controllers/ShoppingListController.cs
> +        [HttpPost("/shopping-list/add")]
I think I'm more happy with `shoppinglist` instead of `shopping-list` naming but it's up to you at this point.

2020-09-27 20:21 UTC, MFatihMAR commented on efurni-api/Startup.cs
> +            services.AddSingleton<IConnectionMultiplexer>(ConnectionMultiplexer.Connect("localhost"));
grab it from config, do not hardcore it!

2020-09-27 20:21 UTC, MFatihMAR commented on efurni-api/Controllers/SubscriptionController.cs
> +        efurniContext _dbContext;
make it `private` explicitly

2020-09-27 20:22 UTC, MFatihMAR requested changes
I think it needs some refactoring overall — please also see my comments, thanks!

2020-09-27 20:34 UTC, PhantomCloak commented on efurni-api/Controllers/ProductController.cs
> +        [HttpGet("/products/popular")]
it hasn't additional root path so in that case, the endpoint path will be `host.com/product/popular`

2020-09-28 12:48 UTC, PhantomCloak commented on efurni-api/Controllers/ProductController.cs
> +            return Ok(products);
I prefer in this way, IMO making line responsibility simple, and breaking down to pieces helps both reader and writer

2020-09-28 12:59 UTC, PhantomCloak commented
Fixed all of the issues mentioned above

2020-09-28 14:44 UTC, MFatihMAR approved these changes
🔥

2020-09-28 14:45 UTC, merged